# Generated by Django 5.2.12 on 2026-03-04 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Required. A valid email address.', max_length=255, unique=True, verbose_name='Email Address')),
                ('user_type', models.CharField(choices=[('STAFF', 'Staff'), ('CLIENT', 'Client')], default='CLIENT', help_text='Determines which portal the user can access.', max_length=10, verbose_name='User Type')),
                ('is_verified', models.BooleanField(default=False, help_text='Indicates if the email has been verified.', verbose_name='Email Verified')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into admin site.', verbose_name='Staff Status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='Active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the user joined.', verbose_name='Date Joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'accounts_user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, help_text="User's full legal name.", max_length=255, verbose_name='Full Name')),
                ('company', models.CharField(blank=True, help_text='Company or organization name.', max_length=255, verbose_name='Company')),
                ('job_title', models.CharField(blank=True, help_text='Current job title or occupation.', max_length=255, verbose_name='Job Title')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number.', max_length=20, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, help_text='Physical address.', verbose_name='Address')),
                ('kyc_verified', models.BooleanField(default=False, help_text='Know Your Customer verification status.', verbose_name='KYC Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this profile was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this profile was last updated.', verbose_name='Updated At')),
                ('user', models.OneToOneField(help_text='The user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client Profile',
                'verbose_name_plural': 'Client Profiles',
                'db_table': 'accounts_client_profile',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('LABOR', 'Labor')], default='LABOR', help_text='Staff role: Admin or Labor.', max_length=10, verbose_name='Role')),
                ('assigned_permissions', models.TextField(blank=True, help_text='Comma-separated list of special permissions.', verbose_name='Assigned Permissions')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this profile was created.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this profile was last updated.', verbose_name='Updated At')),
                ('user', models.OneToOneField(help_text='The user this profile belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
                'db_table': 'accounts_staff_profile',
            },
        ),
    ]
