# Generated by Django 5.2.12 on 2026-03-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                db_index=True,
                help_text="Required. A valid email address.",
                max_length=255,
                unique=True,
                verbose_name="Email Address",
            ),
        ),
    ]
