# Generated by Django 5.2.17 on 2026-09-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="kyc_document",
            field=models.FileField(
                blank=True,
                help_text="Identity document for verification (PDF/JPG/PNG).",
                null=True,
                upload_to="kyc/",
                verbose_name="KYC Document",
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="kyc_rejection_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Why staff rejected the document.",
                max_length=500,
                verbose_name="KYC Rejection Reason",
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("UNVERIFIED", "Unverified"),
                    ("PENDING", "Pending Review"),
                    ("VERIFIED", "Verified"),
                    ("REJECTED", "Rejected"),
                ],
                default="UNVERIFIED",
                help_text="KYC verification state machine.",
                max_length=20,
                verbose_name="KYC Status",
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="kyc_submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the document was last submitted.",
                null=True,
                verbose_name="KYC Submitted At",
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="kyc_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When staff approved the document.",
                null=True,
                verbose_name="KYC Verified At",
            ),
        ),
    ]
