# Generated by Django 5.2.12 on 2026-03-07 13:47

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current wallet balance.",
                        max_digits=12,
                        verbose_name="Balance",
                    ),
                ),
                (
                    "is_frozen",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the wallet is frozen (no operations allowed).",
                        verbose_name="Frozen",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this wallet was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this wallet was last updated.",
                        verbose_name="Updated At",
                    ),
                ),
                (
                    "client_profile",
                    models.OneToOneField(
                        help_text="The client profile associated with this wallet.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="accounts.clientprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "db_table": "wallet_wallet",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Transaction amount.",
                        max_digits=12,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DEPOSIT", "Deposit"),
                            ("WITHDRAWAL", "Withdrawal"),
                            ("TRANSFER", "Transfer"),
                        ],
                        help_text="Type of transaction.",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("FLAGGED", "Flagged"),
                        ],
                        default="PENDING",
                        help_text="Current transaction status.",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Transaction description or notes.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        help_text="Unique reference for idempotency.",
                        max_length=100,
                        unique=True,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data for audit trail.",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="When this transaction was created.",
                        verbose_name="Created At",
                    ),
                ),
                (
                    "counterparty_wallet",
                    models.ForeignKey(
                        blank=True,
                        help_text="The counterparty wallet (for transfers).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counterparty_transactions",
                        to="wallet.wallet",
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        help_text="The primary wallet for this transaction.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "wallet_transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["created_at"], name="wallet_tran_created_fb97c1_idx"),
                    models.Index(fields=["status"], name="wallet_tran_status_a49b73_idx"),
                    models.Index(fields=["type"], name="wallet_tran_type_fa9e01_idx"),
                    models.Index(
                        fields=["wallet", "created_at"],
                        name="wallet_tran_wallet__a053af_idx",
                    ),
                ],
            },
        ),
    ]
