# Generated by Django 5.2.12 on 2026-03-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0002_alter_transaction_status_alter_transaction_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                    ("FLAGGED", "Flagged"),
                ],
                default="PENDING",
                help_text="Current transaction status.",
                max_length=10,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("TRANSFER", "Transfer"),
                ],
                help_text="Type of transaction.",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
