# Generated by Django 5.2.12 on 2026-03-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_transaction_status_alter_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallet",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Additional wallet metadata (freeze info, flags, etc.).",
                verbose_name="Metadata",
            ),
        ),
    ]
