# Generated by Django 5.2.17 on 2026-09-21 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_wallet_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("DEPOSIT", "Deposit"),
                    ("WITHDRAWAL", "Withdrawal"),
                    ("TRANSFER", "Transfer"),
                    ("FEE", "Fee"),
                ],
                help_text="Type of transaction.",
                max_length=10,
                verbose_name="Type",
            ),
        ),
    ]
